### ISSUE TITLE
Handling no records found

### ISSUE THREAD

**Issue by gauravpadia** [fivesqrd/bego#1]
Hi,

Thank you for this dynamodb package. It is really beautiful and helpful.

You have given examples to fetch records but how to handle if no records found. 

For example: 

`$item = $music->fetch(
    'Bob Dylan', 'How many roads'
);`

It may or may not find any records. Then how to handle that case ? 

I have tried to do fetch with a not existing partition key and it throws an error:

`Argument 1 passed to Aws\\DynamoDb\\Marshaler::unmarshalItem() must be of the type array, null given, called in /public_html/vendor/fivesqrd/bego/src/Table.php on line 41`

Any insights would be helpful.

Thanks.

Kind Regards

**Comment by christianjburger** [comment]
good catch @gauravpadia there is indeed no support for an empty fetch result.

I've pushed an update now that checks for this. An empty fetch result will now return an empty item object. The object can be tested for emptiness as in the example below:

```
/* Fetch an item */
$item = $music->fetch(
    'Bob Dylan', 'How many paths'
);

if ($item->isEmpty()) {
    throw new \Exception("Requested record could not be found");
}

if ($item->isSet('hit')) {
    echo "{$item->attribute('SongTitle')} is a hit";
}

echo $item->attribute('Id');
```

**Comment by gauravpadia** [comment]
Awesome. Thanks!
