### ISSUE TITLE
Query without partition key

### ISSUE THREAD

**Issue by gauravpadia** [fivesqrd/bego#2]
Hi,

How to query without partition key known ? 

I have a two tables, one "users" table having "user_id" as partition key and second "configuration" table having "configuration_id" as partition key and it also have "user_id" as sort key. Now I have to find all the records related to specific user id. 

Is it possible ? 

I tried following but without key it is not working

`
$configuration_table->query()->condition(Condition::comperator('user_id', '=', $client_id))->fetch()
`

**Comment by gauravpadia** [comment]
Ok I think it required using "scan" then, right ? Sorry I am new to dynamoDB.

I tried using scan as below but it gives me an error:

`
$configuration_table->scan()->filter(Condition::comperator('user_id', '=', $client_id))->fetch()
`

Error:
`
Call to undefined method Bego\\Scan\\Conduit::option()
in file /vendor\/fivesqrd\/bego\/src\/Component\/Paginator.php
on line no 65
`

**Comment by gauravpadia** [comment]
Hi,

Okay I saw `Scan/Conduit.php` class is missing option method. I copied it from `Query/Conduit.php` and it started working. Please update. 

Also in your guide "Working with result sets" `$item['Id']` doesn't work and throws an error, it should be `$item->attribute('Id')` or first get all attributes `$item = $item->attributes()` and then `$item['Id']`

Thanks.

**Comment by christianjburger** [comment]
cool, fix applied to Scan\Conduit class and README updated with the correct way to access the item's attributes (v0.17.4)
