### ISSUE TITLE
Add support for ProjectionExpression for scan and query

### ISSUE THREAD

**Issue by gauravpadia** [fivesqrd/bego#3]
Hi,

Please add support for "ProjectionExpression" for scan and query to get only specific attributes instead of all attributes.

_A Scan operation reads every item in a table or a secondary index. By default, a Scan operation returns all of the data attributes for every item in the table or index. You can use the ProjectionExpression parameter so that Scan only returns some of the attributes, rather than all of them._ 

Thanks.

**Comment by christianjburger** [comment]
hi, ProjectionExpression is now supported (0.18.0 and up)

**Comment by gauravpadia** [comment]
Hi, 

ProjectionExpression support added, thanks so much for that but it is only working with query not working with scan. 

Can you please add support to scan statement too ? 

Thanks.

**Comment by christianjburger** [comment]
Hi there, 

Support for ProjectionExpression in scans has been added in v0.20.0
