### ISSUE TITLE
Create Item error

### ISSUE THREAD

**Issue by gauravpadia** [fivesqrd/bego#4]
HI,

When creating item it is generating an error on line 76 in file `src/Put/Statement.php`

Currently it is `$result = $client->putItem($this->compile());` but I think it should be `$result = $this->_db->client()->putItem($this->compile());`

Please update.

Thanks.

**Comment by christianjburger** [comment]
hi there, this has been fixed in 0.19.1. Thanks.

**Comment by gauravpadia** [comment]
Oh it is still giving error. You have just changed `$client` to `$this->_db` but isn't it should be `$this->_db->client()` ?

**Comment by christianjburger** [comment]
you're right :) fixed in 0.19.2. Thanks.
